export const SET_TODO_LIST_ACTION = 'SET_TODO_LIST_ACTION'
export const ADD_TODO_ACTION = 'ADD_TODO_ACTION'
export const REMOVE_TODO_ACTION = 'REMOVE_TODO_ACTION'
export const COMPLETE_TODO_ACTION = 'COMPLETE_TODO_ACTION'
